import { Open_Sans } from "next/font/google";
const inter = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function ConferenceLayout({ children }) {
	return (
		<>
			<html lang="en" className={inter.className}>
				<body>
					<main>{children}</main>
				</body>
			</html>
		</>
	);
}
